In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


In [3]:
# Print the data type of both variables
print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'list'>
Data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in the list
print("Data type of each element in list_:")
for element in list_:
    print(f"Element: {element}, Data type: {type(element)}")

# Print the data type of each element in the NumPy array
print("\nData type of each element in array_list:")
for element in array_list:
    print(f"Element: {element}, Data type: {type(element)}")


Data type of each element in list_:
Element: 1, Data type: <class 'str'>
Element: 2, Data type: <class 'str'>
Element: 3, Data type: <class 'str'>
Element: 4, Data type: <class 'str'>
Element: 5, Data type: <class 'str'>

Data type of each element in array_list:
Element: 1, Data type: <class 'numpy.str_'>
Element: 2, Data type: <class 'numpy.str_'>
Element: 3, Data type: <class 'numpy.str_'>
Element: 4, Data type: <class 'numpy.str_'>
Element: 5, Data type: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


In [5]:
import numpy as np

# Original list and array
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(f"Element: {element}, Data type: {type(element)}")

# Print the data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(f"Element: {element}, Data type: {type(element)}")

# num_list and num_array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print the data type of each element in num_list
print("\nData type of each element in num_list:")
for row in num_list:
    for element in row:
        print(f"Element: {element}, Data type: {type(element)}")

# Print the data type of each element in num_array
print("\nData type of each element in num_array:")
for row in num_array:
    for element in row:
        print(f"Element: {element}, Data type: {type(element)}")


Data type of each element in list_:
Element: 1, Data type: <class 'str'>
Element: 2, Data type: <class 'str'>
Element: 3, Data type: <class 'str'>
Element: 4, Data type: <class 'str'>
Element: 5, Data type: <class 'str'>

Data type of each element in array_list:
Element: 1, Data type: <class 'numpy.int64'>
Element: 2, Data type: <class 'numpy.int64'>
Element: 3, Data type: <class 'numpy.int64'>
Element: 4, Data type: <class 'numpy.int64'>
Element: 5, Data type: <class 'numpy.int64'>

Data type of each element in num_list:
Element: 1, Data type: <class 'int'>
Element: 2, Data type: <class 'int'>
Element: 3, Data type: <class 'int'>
Element: 4, Data type: <class 'int'>
Element: 5, Data type: <class 'int'>
Element: 6, Data type: <class 'int'>

Data type of each element in num_array:
Element: 1, Data type: <class 'numpy.int64'>
Element: 2, Data type: <class 'numpy.int64'>
Element: 3, Data type: <class 'numpy.int64'>
Element: 4, Data type: <class 'numpy.int64'>
Element: 5, Data type: <class

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


In [6]:
import numpy as np

# Define num_list and num_array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find and print the shape and size of num_array
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [7]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))

# Print the created array, its shape, and size
print("Array of 3x3 matrix containing zeros:\n", zeros_array)
print("Shape of the array:", zeros_array.shape)
print("Size of the array:", zeros_array.size)


Array of 3x3 matrix containing zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of the array: (3, 3)
Size of the array: 9


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
